# note, same network must be used in provision/etc/salt/minion.d/99-master.conf file
net_ip: "192.168.150"
# https://www.vagrantup.com/docs/provisioning/salt#install_type
# also possible to specify exact version i.e: "stable 3001.2"
install_type: "stable 3001"
master:
  os: "bento/centos-8"
  py_ver: "3"
  host_name: 'saltmaster.local'
  # note, same IP must be used in provision/etc/salt/minion.d/99-master.conf file
  # last IP octet for master VM
  ip: "10"
  synced_folders:
    # src path is relative to current directory
    # - ["src", "dst"]
    - ["./salt/files",  "/srv/salt/files"]
    # use folder in parent directory
    # - ["../../formulas-public", "/srv/salt/formulas-public"]
minions:
  # ["minion-name",  "last IP octet ", "RAM in MB", "image", "python major version"]
  - ["minion-centos8",  "11", "1024", "bento/centos-8",  "3"]
  - ["minion-debian10", "12", "1024", "bento/debian-10", "3"]
